---

- hosts: all
    become: true
    tasks:
        - name: Install programs
          apt: name={{ item }} state=installed
          with_items:
            - nginx
            - npm
            - git
            - node
            - nodejs
          
        