# -*- mode: ruby -*-
# vi: set ft=ruby :

$set_environment_variables_ui = <<SCRIPT
tee "/etc/profile.d/myvars.sh" > "/dev/null" <<EOF
# environment variables.
export BACK_HOST='192.168.55.6'
EOF
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.55.5"
  config.vm.hostname = "UI"
  config.disksize.size = '70GB'

  config.vm.provider "virtualbox" do |vb|
    vb.name = "VM_UI"
    vb.cpus = 2
    vb.memory = 2048
   end
 
  config.vm.provision "shell", inline: $set_environment_variables_ui
  config.vm.provision "shell", path: 'initial_programs_ui.sh'
end
